version: '3.9'

services:
  wb-db:
    image: mongo:latest
    container_name: ${MONGO_HOST} 
    ports:
      - '${MONGO_PORT}:${MONGO_PORT}'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER} 
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
    volumes:
      - mongodb:/data/db
    networks:
      - db
  wellness-bot:
    container_name: wellness-bot
    # env file specification required due to build context
    env_file: 
      - ../.env
    build:
      context: ../ 
      dockerfile: docker/x86/Dockerfile
    environment:
      MONGO_USER: ${MONGO_USER}
      MONGO_PASS: ${MONGO_PASS}
      MONGO_PORT: ${MONGO_PORT}
      MONGO_HOST: ${MONGO_HOST} 
    depends_on:
      - wb-db
    networks:
      - db

volumes:
  mongodb:

networks:
  db:
    driver: bridge